-- Create event check-ins table
CREATE TABLE IF NOT EXISTS event_checkins (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  phone_number TEXT NOT NULL,
  email TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE event_checkins ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows anyone to insert (for check-ins)
CREATE POLICY "Anyone can check in" ON event_checkins
  FOR INSERT
  TO anon
  WITH CHECK (true);

-- Create a policy that only authenticated users can view check-ins (for admin)
CREATE POLICY "Only authenticated users can view check-ins" ON event_checkins
  FOR SELECT
  TO authenticated
  USING (true);

-- Create an index on email for faster lookups
CREATE INDEX IF NOT EXISTS idx_event_checkins_email ON event_checkins(email);

-- Create an index on created_at for sorting
CREATE INDEX IF NOT EXISTS idx_event_checkins_created_at ON event_checkins(created_at);